---
- name: Install KVM packages
  package:
    name:
      - qemu-kvm
      - libvirt
      - libguestfs-tools
      - virt-install
    state: present

- name: Define virtual network
  virt_net:
    command: define
    name: "{{ virt_network_name }}" 
    xml: "{{ lookup('template', 'network.j2') }}"
    autostart: yes

- name: Start virtual network
  virt_net:
    command: start 
    name: "{{ virt_network_name }}" 
    autostart: yes
