---
- name: Ensure pkgs installed (RHEL 8)
  package:
    name: "{{ rhel8_pkgs }}"
    state: latest
  tags: initial_setup
  when: ansible_distribution_version|int == 8

- name: Ensure pkgs installed (RHEL 7)
  package:
    name: "{{ rhel7_pkgs }}"
    state: latest
  tags: initial_setup
  when: ansible_distribution_version|int == 7
