---
  
- name: Stopping VM {{ vm }}
  virt:
    state: destroyed
    name: "{{ vm }}"
  retries: 3
  delay: 2

- name: Delete VM {{ vm }}
  virt:
    command: undefine
    name: "{{ vm }}"

- name: Cleanup storage {{ vm }}
  file:
    path: '{{ vm_files_path }}/{{ vm }}.qcow2'
    state: absent
