---
- name: Get VMs
  virt:
    command: list_vms
  register: vmlist
  
- name: Cleanup VMs 
  include_tasks: 
    file: ./delete.yml
  vars:
    vm: "{{ item }}" 
  with_items: "{{ vmlist.list_vms }}"
  when: item != bastion_vm_hostname_short
