openshift_version: 4.2
openshift_z_version: 4.2.18
rhcos_version: 4.2.18
rhcos_kernel: rhcos-4.2.18-x86_64-installer-kernel
rhcos_initramfs: rhcos-4.2.18-x86_64-installer-initramfs.img
rhcos_biosimg: "rhcos-4.2.18-x86_64-metal-bios.raw.gz"
rhcos_kernel_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/{{ rhcos_kernel }}"
rhcos_initramfs_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/{{ rhcos_initramfs }}"
rhcos_biosimg_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/{{ rhcos_biosimg }}"
openshift_clusternet: 10.8.0.0/14
openshift_clusternetprefix: 23
openshift_servicenet: 172.30.0.0/16
openshift_clustername: ocp4
openshift_routedomain: apps
openshift_installer_dir: "/home/{{ bastion_cloud_user }}/{{ openshift_clustername }}"
openshift_upgrade: false
openshift_smoke_tests_must_succeed: true
network_domain: example.com
network_subdomain: "{{ openshift_clustername }}.{{ network_domain }}"

# define the following in secrets file
#admin_user: admin
#admin_password: something
#developer_user: developer
#developer_password: something

virt_network_name: ocp4
virt_network_ip: 192.168.50.1
virt_network_mask: 255.255.255.0
virt_network_bridge_name: br1
virt_network_reverse_lookup: 50.168.192
virt_network: "192.168.50.0/24"

vm_ssh_key: /home/ec2-user/glsdev.pub
vm_ssh_private_key: glsdev
vm_ssh_private_key_location: /home/ec2-user/glsdev

vm_files_path: /images/openshift

bastion_vm_disksize: 10G
bastion_vm_macaddress: "52:54:00:7d:2d:01"
bastion_vm_ipaddress: "192.168.50.100"
bastion_vm_vcpu: 2
bastion_vm_memory_gb: 4
bastion_vm_hostname_short: utility
bastion_vm_hostname: "{{bastion_vm_hostname_short}}.{{network_subdomain}}"
bastion_vm_disk_image: "{{vm_files_path}}/{{bastion_vm_hostname_short}}.qcow2"
bastion_vm_cloud_init_iso: "{{vm_files_path}}/{{bastion_vm_hostname_short}}-ci.iso"
bastion_cloud_user: helper

nfs_server_exports_size: 200G
nfs_registry: true

rhel_qcow_image: "/images/rhel-8.1-x86_64-kvm.qcow2"

disable_default_repos: false
rhel_repos:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms

workers:
  - name: "worker01"
    disksize: 40G
    macaddress: "52:54:00:7d:2d:14"
    ipaddress: "192.168.50.150"
    vcpu: 4
    memory_gb: 16
  - name: "worker02"
    disksize: 40G
    macaddress: "52:54:00:7d:2d:15"
    ipaddress: "192.168.50.151"
    vcpu: 4
    memory_gb: 16

configure_htpasswd_auth: true
