---
# tasks file for roles/configure_storage
- name: Creating QCOW2 disk - PCIe NVME disk
  delegate_to: localhost
  shell:
    cmd: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2 {{ vm_disksize }}"
  tags:
    - provisioning_libvirt

- name: Ensure correct permission
  delegate_to: localhost
  file:
    path: '/var/lib/libvirt/images/{{ inventory_hostname }}.qcow2'
    mode: u+rw,g-rwx,o-rwx
  tags:
    - provisioning_libvirt

# - name: refresh storage pool
#   run_once: true
#   delegate_to: localhost
#   shell: virsh pool-refresh "{{ item }}"
#   with_items: "{{ libvirt_storage_pool }}"
#   tags:
#     - provisioning_libvirt
#     - refresh_storage_pool
