---
- name: Make sure firewall service is running
  service:
    name: firewalld
    enabled: true
    state: restarted

- name: Allowing firewall rules for services
  firewalld:
    service: "{{ item }}"
    zone: external
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ allowed_services }}"

- name: Allowing firewall rules for ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ allowed_ports }}"
