---
- name: Generate Worker Inventory
  become: false
  hosts: localhost
  gather_facts: false
  roles:
    - create_worker_inventory

- name: Preparing and Configuring DHCP and PXE Configs
  become: true
  hosts: helper_vm
  gather_facts: false
  roles:
    - configure_dns
    - configure_dhcpconfig
    - configure_pxeconfig
    - configure_lbconfig
    - configure_ignitionfiles

- name: Update Bastion
  become: true
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Drop DNS forwarder into DNSMasq for OpenShift subdomain
      template:
        src: ./files/dnsmasq.j2
        dest: /etc/dnsmasq.d/ocp4.conf
      when: ocp_dns_server is defined

- name: Preparing and Deploying VM on Libvirt
  become: true
  hosts: ocp4_nodes
  gather_facts: false
  roles:
    - configure_storage
    - deploy_ocpvms
