---
- name: Preparing and Configuring DHCP and PXE Configs
  become: true
  hosts: helper_vm
  gather_facts: false
  roles:
    - configure_dns
    - configure_dhcpconfig
    - configure_pxeconfig
    - configure_lbconfig
    - configure_ignitionfiles

- name: Preparing and Deploying VM on Libvirt
  become: true
  hosts: ocp4_nodes
  gather_facts: false
  roles:
    - configure_storage
    - deploy_ocpvms
