---
- name: Generate Worker Inventory
  become: false
  hosts: localhost
  gather_facts: false
  roles:
    - create_worker_inventory
      
- name: Deleting VM on Libvirt
  become: true
  hosts: localhost
  gather_facts: false
  roles:
    - destroy_nodes
