---
- name: Define NFS disk
  parted:
    device: /dev/vdb
    number: 1
    state: present

- name: Create NFS filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vdb1

- name: Create mount point
  file:
    state: directory
    path: /exports
    owner: root
    group: root
    mode: 0777

- name: Mount NFS filesystem
  mount:
    path: /exports
    src: /dev/vdb1
    fstype: xfs
    state: mounted

- name: Create exports
  template:
    src: exports.j2
    dest: /etc/exports

- name: Enable NFS service
  service:
    name: nfs-server
    enabled: yes
    state: started

- name: Enable RPC service
  service:
    name: rpcbind
    enabled: yes
    state: started
