---
- name: Generate Worker Inventory
  become: false
  hosts: localhost
  gather_facts: false
  roles:
    - create_worker_inventory

- name: Install OpenShift
  become: false
  hosts: helper_vm
  gather_facts: false
  roles:
    - do_ocp_install
