---
- name: Creating, Preparing, and Configuring Helper Node
  become: true
  hosts: helper_vm
  gather_facts: true
  roles:
   - configure_network
   - create_helper
   - install_pkgs
   - configure_firewall
   - configure_selinux
   - configure_http
   - configure_pxe
   - configure_ocpcli
