---
# tasks file for roles/configure_ignitionfiles
- name: Clean up previous working directory
  file:
    path: "{{ openshift_installer_dir }}"
    state: absent
  tags:
    - configure_ignitions_file

- name: Ensure working directory exists
  file:
    path: "{{ openshift_installer_dir }}"
    state: directory
    owner: "{{ bastion_cloud_user }}"
    group: "{{ bastion_cloud_user }}"
    mode: 0775
  tags:
    - configure_ignitions_file

- name: Get Authorized ssh key
  slurp:
    path: "{{ vm_ssh_key }}"
  delegate_to: localhost
  register: sshkeypub

- name: Prepare ignition files
  become: no
  template:
    src: install-config.yaml.j2
    dest: "{{ openshift_installer_dir }}/install-config.yaml"
  tags:
    - configure_ignitions_file

- name: Execute openshift installer file
  become: no
  shell: /usr/bin/openshift-install create ignition-configs --dir={{ openshift_installer_dir }}
  tags:
    - configure_ignitions_file

- name: Ensure web hosting directory exists
  file:
    path: /var/www/html/openshift4/{{ openshift_z_version }}/ignitions/
    state: directory
    owner: apache
    group: root
  tags:
    - configure_ignitions_file

- name: Copy ign file to http hosted folder
  shell: |
    cp -rvf {{ openshift_installer_dir }}/*.ign /var/www/html/openshift4/{{ openshift_z_version }}/ignitions/
    chmod 744 /var/www/html/openshift4/{{ openshift_z_version }}/ignitions/*
  tags:
    - configure_ignitions_file

- name: Restore SELinux fcontext /var/www/html
  command: restorecon -RFv /var/www/html
  tags:
    - configure_ignitions_file
